backend = "glx";
vsync = false;

corner-radius = 0;
round-borders = 0;

inactive-opacity = 0.90;
active-opacity = 0.90;
frame-opacity = 0.90;

shadow = false;
fading = false;
animations = false;
blur-method = "none";
